'name': 'CI'

'on':
  'pull_request':
  'push':
    'branches':
      - 'main'

'permissions':
  'contents': 'read'

'jobs':
  'gitleaks':
    'name': 'Gitleaks'
    'runs-on': 'ubuntu-latest'
    'steps':
      - 'uses': 'actions/checkout@v6'
        'with':
          'fetch-depth': 0
      - 'uses': 'gitleaks/gitleaks-action@v2'
        'env':
          'GITHUB_TOKEN': '${{ secrets.GITHUB_TOKEN }}'
          'GITLEAKS_ENABLE_UPLOAD_ARTIFACT': 'false'

  'nix':
    'name': 'Nix flake check'
    'runs-on': 'ubuntu-latest'
    'steps':
      - 'uses': 'actions/checkout@v6'
      - 'uses': 'DeterminateSystems/nix-installer-action@v22'
      - 'run': 'nix flake check --print-build-logs'

  'pipeline-complete':
    'name': 'Pipeline Complete'
    'if': '${{ always() }}'
    'needs':
      - 'gitleaks'
      - 'nix'
    'runs-on': 'ubuntu-latest'
    'steps':
      - 'uses': 're-actors/alls-green@release/v1'
        'with':
          'jobs': '${{ toJSON(needs) }}'
